# Generated by Django 5.1.1 on 2024-09-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ais', '0002_alter_students_nim_alter_teachers_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='nip',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
